### ISSUE TITLE
Rediriger simuler.mes-aides.gouv.fr vers mes-aides.gouv.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-campaign#3]
- La campagne est terminée.
- Le certificat SSL expire dans deux semaines.
- Il n'y a presque plus de trafic entrant :
![capture d ecran 2017-05-17 a 10 55 56](https://cloud.githubusercontent.com/assets/222463/26146161/74f1f496-3aef-11e7-9dd7-eab431511544.png)

…on peut donc rediriger en `302` vers `mes-aides.gouv.fr`.

**Comment by guillett** [comment]
Ayant fait le même constat de fin de campagne j'ai déjà mis en place cette redirection hier à la réinitialisation du serveur dédié.

Seul hic, le certificat SSL pour simuler.gouv.fr n'est plus sur la machine donc les personnes allant directement sur https://simuler.mes-aides.gouv.fr ont une erreur de certificat.

Comme discuté IRL, pas d'action supplémentaire à faire.
